const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/img/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
        _id: "2",
        name: "D&G Slim Pants",
        category: "Pants",
        image: "/img/p2.jpg",
        price: 70,
        countInStock: 5,
        brand: "D&G",
        rating: 4.0,
        numReviews: 17,
        description: "High quality product",
      },
      {
        _id: "3",
        name: "Nike Slim Pants",
        category: "Pants",
        image: "/img/p3.jpg",
        price: 89,
        countInStock: 22,
        brand: "Nike",
        rating: 3.5,
        numReviews: 12,
        description: "High quality product",
      },
      {
        _id: "4",
        name: "Nike Fit Pant",
        category: "Pants",
        image: "/img/p4.jpg",
        price: 189,
        countInStock: 8,
        brand: "Nike",
        rating: 4.5,
        numReviews: 20,
        description: "High quality product",
      },
      {
        _id: "5",
        name: "Puma Slim Pant",
        category: "Pants",
        image: "/img/p5.jpg",
        price: 65,
        countInStock: 6,
        brand: "Puma",
        rating: 4.5,
        numReviews: 30,
        description: "High quality product",
      },
      {
        _id: "6",
        name: "Adidas Fit Pant",
        category: "Pants",
        image: "/img/p6.jpg",
        price: 139,
        countInStock: 0,
        brand: "Adidas",
        rating: 2.5,
        numReviews: 18,
        description: "High quality product",
      },
      
  ],
};

export default data;